openapi: 3.2.0
info:
  title: Cadasto Additional Admin API
  version: 1.0.0
  description: 'Additional API on top of the openEHR REST API, specific to Cadasto.

    The endpoints in this specification are Cadasto-specific and are intended

    to make it easier for app builders to interact with openEHR (e.g. datamaps).

    This API only works within Cadasto.'
servers:
- url: https://api.customer.cadasto.io
security:
- bearerAuth: []
tags:
- name: Admin
  description: Admin-only actions, such as permanently deleting (destroy) episodes.
paths:
  /extra/v1/admin/ehr/{ehrUid}/episode/{uid}/destroy:
    parameters:
    - $ref: '#/components/parameters/ehrUidPath'
    - $ref: '#/components/parameters/uid'
    put:
      tags:
      - Admin
      summary: Destroy episode (admin)
      description: Permanently deletes an episode (admin-only).
      responses:
        '200':
          description: OK
        '404':
          description: Not found
      operationId: putExtraV1AdminEhrByEhrUidEpisodeByUidDestroy
      x-operation-id-source: derived
components:
  parameters:
    uid:
      name: uid
      in: path
      required: true
      schema:
        type: string
    ehrUidPath:
      name: ehrUid
      in: path
      required: true
      schema:
        type: string
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
x-ext-urls: {}
